version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":github:"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":whale:"
